title: "Mr. Abarnan Rajkhowa"
description: "Lecturer, Computer Science & Engineering | Hailakandi Polytechnic, Assam"
baseurl: "" # leave empty unless site is inside a subfolder
url: "https://arajkho.github.io" # replace with your site URL

# Logo / Photo
logo: "https://raw.githubusercontent.com/Arajkho/site/main/download.jpg"

# Author information
author:
  name: "Abarnan Rajkhowa"
  role: "Lecturer, Computer Science & Engineering"
  location: "Hailakandi Polytechnic, Assam"
  email: "your-email@example.com"   # optional
  github: "Arajkho"
  linkedin: "your-linkedin-profile" # replace if you want

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Notice"
    url: "/notice/"
  - title: "Courses"
    url: "/courses/"
  - title: "Research"
    url: "/research/"
  - title: "Contact"
    url: "/contact/"

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
