title: "Mr. Abarnan Rajkhowa"
description: "Designation: Lecturer, Computer Science & Engineering | TPO(i/c),Scholarship INO, SpringBoard SPOC | Hailakandi Polytechnic, Assam"
baseurl: "/site" 
url: "https://arajkho.github.io" # replace with your site URL

# Logo / Photo
logo: "https://raw.githubusercontent.com/Arajkho/site/main/download.jpg"

# Author information
author:
  name: "Abarnan Rajkhowa"
  role: "Designation: Lecturer, Computer Science & Engineering | TPO(i/c),Scholarship INO, SpringBoard SPOC | "
  location: "Hailakandi Polytechnic, Assam"
  about: |
    ### Institutional Roles
    - Training & Placement Officer (TPO) Incharge  
    - Infosys Springboard SPOC  
    - Scholarship Institutional Nodal Officer  

    ### Personal Information
    - Passionate reader, learner, educator & coder  
    - Qualified GATE CS (2020, 2023, 2024) with 500+ score  
    - Strong interest in academics, research & student mentorship  

# Navigation links
nav_links:
  - title: "Home"
    url: "/index.md"
  - title: "Notices"
    url: "/notices/"
  - title: "Courses"
    url: "/courses/"
  - title: "TPO Desk"
    url: "/tpo/"
  - title: "Scholarship Information"
    url: "/scholarship/"
  - title: "Springboard SPOC"
    url: "/springboard/"
  - title: "Research"
    url: "/research/"
  - title: "About"
    url: "/about.md"
  - title: "Contact"
    url: "/contact/"

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
