title: "Abarnan Rajkhowa"
description: "Lecturer in CSE | Sharing notes, projects & courses"
logo: "/assets/images/logo.png"   # replace with your logo path if available
theme: minima   # clean default Jekyll theme
lang: en-US

# Author Info
author:
  name: "Abarnan Rajkhowa"
  role: "Lecturer in Computer Science & Engineering"
  location: "Assam, India"
  email: "your-email@example.com"

# Social Links
github_username: abarnanrajkhowa
linkedin_username: your-linkedin
twitter_username: your-twitter

# Navigation Tabs
nav_links:
  - title: "Home"
    url: "/"
  - title: "Courses"
    url: "/courses"
  - title: "Projects"
    url: "/projects"
  - title: "Contact"
    url: "/contact"

# Plugins
plugins:
  - jekyll-seo-tag
